name: arxiv
channels:
  - conda-forge
dependencies:
  - aiohttp=3.8.6=py310hd125d64_1
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - anyio=3.7.1=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - arxiv=1.4.8=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - black=23.10.1=py310hbe9552e_0
  - brotli=1.1.0=hb547adb_1
  - brotli-bin=1.1.0=hb547adb_1
  - brotli-python=1.1.0=py310h1253130_1
  - bzip2=1.0.8=h3422bc3_4
  - ca-certificates=2023.7.22=hf0a4a13_0
  - cachetools=5.3.2=pyhd8ed1ab_0
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.16.0=py310hdcd7c05_0
  - charset-normalizer=3.3.1=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.1.1=py310h38f39d4_1
  - cryptography=41.0.5=py310h0e6f4b3_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dataclasses-json=0.5.7=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - et_xmlfile=1.1.0=pyhd8ed1ab_0
  - exceptiongroup=1.1.3=pyhd8ed1ab_0
  - feedparser=6.0.10=pyhd8ed1ab_0
  - fonttools=4.43.1=py310hd125d64_0
  - freetype=2.12.1=hadb7bae_2
  - frozenlist=1.4.0=py310h2aa6e3c_1
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.40=pyhd8ed1ab_0
  - google-api-core=2.12.0=pyhd8ed1ab_0
  - google-auth=2.23.4=pyhca7485f_0
  - googleapis-common-protos=1.61.0=pyhd8ed1ab_0
  - greenlet=3.0.1=py310hd5a4765_0
  - idna=3.4=pyhd8ed1ab_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - jsonpatch=1.33=pyhd8ed1ab_0
  - jsonpointer=2.4=py310hbe9552e_3
  - kiwisolver=1.4.5=py310h38f39d4_1
  - langchain=0.0.327=pyhd8ed1ab_0
  - langsmith=0.0.56=pyhd8ed1ab_0
  - lcms2=2.15=hf2736f0_3
  - lerc=4.0.0=h9a09cb3_0
  - libabseil=20230802.1=cxx17_h13dd4ca_0
  - libblas=3.9.0=19_osxarm64_openblas
  - libbrotlicommon=1.1.0=hb547adb_1
  - libbrotlidec=1.1.0=hb547adb_1
  - libbrotlienc=1.1.0=hb547adb_1
  - libcblas=3.9.0=19_osxarm64_openblas
  - libcxx=16.0.6=h4653b0c_0
  - libdeflate=1.19=hb547adb_0
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=13_2_0_hd922786_1
  - libgfortran5=13.2.0=hf226fd6_1
  - libjpeg-turbo=3.0.0=hb547adb_1
  - liblapack=3.9.0=19_osxarm64_openblas
  - libopenblas=0.3.24=openmp_hd76b1f2_0
  - libpng=1.6.39=h76d750c_0
  - libprotobuf=4.24.4=hc9861d8_0
  - libsqlite=3.43.2=h091b4b1_0
  - libtiff=4.6.0=ha8a6c65_2
  - libwebp-base=1.3.2=hb547adb_0
  - libxcb=1.15=hf346824_0
  - libzlib=1.2.13=h53f4e23_5
  - llvm-openmp=17.0.3=hcd81f8e_0
  - marshmallow=3.20.1=pyhd8ed1ab_0
  - marshmallow-enum=1.5.1=pyh9f0ad1d_3
  - matplotlib-base=3.8.0=py310h9d2df84_2
  - multidict=6.0.4=py310h8e9501a_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - ncurses=6.4=h7ea286d_0
  - numexpr=2.8.7=py310h6e3cc31_4
  - numpy=1.26.0=py310he2cad68_0
  - openai=0.28.1=pyhd8ed1ab_0
  - openapi-schema-pydantic=1.2.4=pyhd8ed1ab_0
  - openjpeg=2.5.0=h4c1507b_3
  - openpyxl=3.1.2=py310h2aa6e3c_1
  - openssl=3.1.4=h0d3ecfb_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.1.2=py310h6e3cc31_0
  - pandas-stubs=2.1.1.230928=pyhd8ed1ab_1
  - pathspec=0.11.2=pyhd8ed1ab_0
  - pathtools=0.1.2=py_1
  - pillow=10.1.0=py310hfae7ebd_0
  - pip=23.3.1=pyhd8ed1ab_0
  - platformdirs=3.11.0=pyhd8ed1ab_0
  - plotly=5.18.0=pyhd8ed1ab_0
  - protobuf=4.24.4=py310hc08086b_0
  - psutil=5.9.5=py310h2aa6e3c_1
  - pthread-stubs=0.4=h27ca646_1001
  - pyasn1=0.5.0=pyhd8ed1ab_0
  - pyasn1-modules=0.3.0=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydantic=1.10.13=py310hd125d64_1
  - pyopenssl=23.3.0=pyhd8ed1ab_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pypdf=3.17.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.12=h01493a6_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-dotenv=1.0.0=pyhd8ed1ab_1
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.10=4_cp310
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0.1=py310h2aa6e3c_1
  - readline=8.2=h92ec313_1
  - regex=2023.10.3=py310h2aa6e3c_0
  - requests=2.31.0=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - scikit-learn=1.3.2=py310h417b086_1
  - scipy=1.11.3=py310hd1cfc7d_1
  - sentry-sdk=1.33.1=pyhd8ed1ab_0
  - setproctitle=1.3.3=py310h2aa6e3c_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - sgmllib3k=1.0.0=pyh9f0ad1d_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - sqlalchemy=2.0.22=py310hd125d64_0
  - stringcase=1.2.0=py_0
  - tenacity=8.2.3=pyhd8ed1ab_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tiktoken=0.5.1=py310hd867425_0
  - tk=8.6.13=hb31c410_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tqdm=4.66.1=pyhd8ed1ab_0
  - types-pytz=2023.3.1.1=pyhd8ed1ab_0
  - typing-extensions=4.8.0=hd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - typing_inspect=0.9.0=pyhd8ed1ab_0
  - tzdata=2023c=h71feb2d_0
  - unicodedata2=15.1.0=py310h2aa6e3c_0
  - urllib3=2.0.7=pyhd8ed1ab_0
  - wandb=0.15.12=pyhd8ed1ab_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hb547adb_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xz=5.2.6=h57fd34a_0
  - yaml=0.2.5=h3422bc3_2
  - yarl=1.9.2=py310hd125d64_1
  - zstd=1.5.5=h4f39d0f_0
  - pip:
      - slack-bolt==1.18.0
      - slack-sdk==3.23.0
prefix: /opt/homebrew/Caskroom/miniforge/base/envs/arxiv
